{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plagueworks-k8-standard-charts.fullname" . }}-configmap
  namespace: {{ include "plagueworks-k8-standard-charts.namespace" . }}
  labels:
    {{- include "plagueworks-k8-standard-charts.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- range $path, $_ := .Files.Glob .Values.configMap.filesGlob }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
{{- end }}