{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "plagueworks-k8-standard-charts.fullname" . }}-ingressroute
  namespace: {{ include "plagueworks-k8-standard-charts.namespace" . }}
  labels:
    {{- include "plagueworks-k8-standard-charts.labels" . | nindent 4 }}
  annotations:
    {{- include "plagueworks-k8-standard-charts.annotations" . | nindent 4 }}
    {{- if .Values.ingress.externalDns.enabled }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.externalDns.target }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: {{ .Values.ingress.externalDns.cloudflareProxied | quote }}
    {{- if .Values.ingress.externalDns.cloudflareComment }}
    external-dns.alpha.kubernetes.io/cloudflare-comment: {{ .Values.ingress.externalDns.cloudflareComment | quote }}
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - kind: Rule
      match: {{ .match | default (printf "Host(`%s`)" .host) }}
      services:
        - name: {{ include "plagueworks-k8-standard-charts.fullname" $ }}-service
          port: {{ $.Values.service.port }}
      {{- if $.Values.ingress.middlewares }}
      middlewares:
        {{- range $.Values.ingress.middlewares }}
        - name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- else }}
    - kind: Rule
      match: {{ .Values.ingress.match | default (printf "Host(`%s`)" .Values.ingress.host) }}
      services:
        - name: {{ include "plagueworks-k8-standard-charts.fullname" . }}-service
          port: {{ .Values.service.port }}
      {{- if .Values.ingress.middlewares }}
      middlewares:
        {{- range .Values.ingress.middlewares }}
        - name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    certResolver: {{ .Values.ingress.tls.certResolver }}
  {{- end }}
{{- end }}